# Generated by Django 4.2.7 on 2023-11-19 05:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        max_length=256,
                        unique=True,
                        verbose_name="Заголовок категории",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "question_id",
                    models.PositiveIntegerField(
                        unique=True, verbose_name="ID вопроса"
                    ),
                ),
                (
                    "question_text",
                    models.TextField(
                        max_length=256, verbose_name="Текст вопроса"
                    ),
                ),
                (
                    "answer_text",
                    models.TextField(
                        max_length=256, verbose_name="Текст ответа"
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="questions",
                        to="question.category",
                        verbose_name="Категория вопроса",
                    ),
                ),
            ],
        ),
    ]
